[WIP] Migrate to newest Actix
ATTENTION maintainers: several of the examples need your expert opinion - they are currently panicking with

```
thread 'main' panicked at '`spawn_local` called from outside of a `task::LocalSet`', .cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/task/local.rs:306:18
```

* Update to latest Actix
* Fix build instructions
* Mark several tests as failing to avoid confusing users